
//date
export const CHANGE_DATE="CHANGE_DATE"
//MODE 
export const CHANGE_MAIN_BLOCK="CALENDAR/CHANGE_MODE"

//TASKS
export const CREATE_TASK="TASKS/CREATE_TASK"
export const CLEAR_ERROR_LIST="CLEAR_ERROR_LIST"
export const SET_TASKS_M="SET_TASKS_M"
export const SET_TASKS_W="SET_TASKS_W"
export const SET_TASKS_D="SET_TASKS_D"
export const SET_ERROR_LIST_T="SET_ERROR_LIST_T"
export const SET_ONE_TASK="SET_ONE_TASK"
//for render 
export const IS_EXISTING_TASK="IS_EXISTING_TASK"
export const IS_TASK_LIST="IS_TASK_LISt"
export const IS_TASK_WIN="OPEN/CLOSE_TASK_WIN"
export const START_LOADING="START/IS_LOADING"
export const END_LOADING="END/IS_LOADING"


//Chat
export const ADD_MESSAGE="CHAT/ADD_MESSAGE"



//todo
export const CREATE_TODO_LIST='TODO/CREATE_TODO_LIST'
export const TODO_BUTTONS='TODO/BUTTONS'
export const DEL_TODO_CARD='TODO/DEL_CARD'
export const CREATE_TODO_TASK='TODO/CREATE_TASK'
export const GET_TODO_HASH='TODO/GET_HASH'
export const CHANGE_TASK_VALUE='TODO/CHANGE_TASK_VALUE'
export const SET_TODOS='SET_TODOS';
export const CHANGE_ID='CHANGE_ID';

//user
export const CHANGE_USER_LIST="CHANGE_USER_LIST";
export const IS_LOGIN='USER/IS_LOGIN';
export const SWITCH_USER_WIN='USER/SWITCH_WINDOW';
export const SET_ERROR_LIST_U='USERS/ERROR_LIST';



//user,render
export const OPEN_APP='OPEN_APP'; 