
//date
export const CHANGE_DATE="CHANGE_DATE"
//MODE 
export const CHANGE_MAIN_BLOCK="CALENDAR/CHANGE_MODE"

//TASKS
export const CREATE_TASK="TASKS/CREATE_TASK"
export const CLEAR_ERROR_LIST="CLEAR_ERROR_LIST"

//for render modale winodw
export const IS_EXISTING_TASK="IS_EXISTING_TASK"
export const IS_TASK_LIST="IS_TASK_LISt"
export const IS_TASK_WIN="OPEN/CLOSE_TASK_WIN"


//Chat
export const ADD_MESSAGE="CHAT/ADD_MESSAGE"



//todo
export const CREATE_TODO_LIST='TODO/CREATE_TODO_LIST'
export const TODO_BUTTONS='TODO/BUTTONS'
export const DEL_TODO_CARD='TODO/DEL_CARD'
export const CREATE_TODO_TASK='TODO/CREATE_TASK'
export const GET_TODO_HASH='TODO/GET_HASH'
export const TODO_ITEM_IS_CHANGED='TODO/ITEM_IS_CHANGED'



//user

export const IS_LOGIN='USER/IS_LOGIN';
export const SWITCH_USER_WIN='USER/SWITCH_WINDOW'